### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by matijakovacevic** [urielcaire/jbility#4]
when building by steps outlined in readme, i get an error on `npm build`

```bash
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/vagrant/www/jbility/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/vagrant/www/jbility/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/vagrant/www/jbility/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)

```

**Comment by matijakovacevic** [comment]
we have added a dislexic font feature, so once we manage to build it, we will open a PR to merge the changes
